name:

on:
  workflow_dispatch:

jobs:
  release-gem:
    name: Release gem on RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          # Use ruby v3.2.6 to use recent rubygems (v3.4.8+).
          # release-gem requires rubygems v3.4.8+, because release-gem uses `gem exec` command and rubygems v3.4.8+ supports it.
          # https://github.com/rubygems/release-gem/blob/a25424ba2ba8b387abc8ef40807c2c85b96cbe32/rubygems-attestation-patch.rb#L40-L45
          ruby-version: 3.2.6
      - uses: rubygems/release-gem@v1
